name: Test

on: [push, pull_request]

jobs:
  test:
    runs-on: [nixos, self-hosted, hoot, dsqr]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
      
      - name: Nix flake checks
        run: nix flake check
        
      - name: Generate coverage
        run: |
          nix develop -c bun run test:coverage:all